### ISSUE TITLE
LatticeReverb Not Working in Audacity 3.X Win64

### ISSUE THREAD

**Issue by ElijahHamilton** [ryukau/VSTPlugins#26] opened 2023-01-26 19:58 UTC
The plugin enables fine, loads up, but outputs no audio.

**Comment by ryukau** [comment] 2023-01-27 02:25
Hi, @ElijahHamilton.

My plugins do nothing, if:

1. Input or output channel count is less than 2.
2. floating point precision is set to double or 64 bit.

Could you confirm that one of above is the case or not? To check 1, create stereo track and try applying LatticeReverb to there. If this is the case, I'll provide more information about it. On 2, I'm not planning to support double precision processing.

Following is the code relevant to this reply.

https://github.com/ryukau/VSTPlugins/blob/9871cb9ab2649811dd6cee2e751bceb1cd9dea74/LatticeReverb/source/plugprocessor.cpp#L113-L118

**Comment by ElijahHamilton** [comment] 2023-01-27 02:34
I tried it on a stereo track, still no output. It makes a repetitive clicking noise in preview mode.
The precision is not set to double/64 bit.

**Comment by ryukau** [comment] 2023-01-27 03:13
I confirmed that my plugins aren't working on Audacity 3.2.3. I'll look into it.

**Comment by ryukau** [comment] 2023-01-27 04:57
The root cause seems like that Audacity doesn't provide `Vst::ProcessData::processContext`.

- [VST 3 Interfaces: ProcessData Struct Reference](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1ProcessData.html)

LatticeReverb started processing when commenting out following part of code.

https://github.com/ryukau/VSTPlugins/blob/9871cb9ab2649811dd6cee2e751bceb1cd9dea74/LatticeReverb/source/plugprocessor.cpp#L100-L109

I'll work on it, but it will take some time.

---

The stutter on stereo track is likely caused by following:

1. Audacity pass input buffer to my plugin.
2. Plugin find that `processContext` is null.
3. Plugin returns early without any processing. It means bypassing is also not done.
4. Audacity plays output buffer that is not updated.
5. Go back to 1.

I was expecting that `processContext` would be provided for any host which primary purpose is audio editing.

LatticeReverb is only using transport state, which is if the host is started playing or not. It resets internal random number generator for each time host starts playing, to trying to output same signal for each play.

**Comment by ryukau** [comment] 2023-01-27 12:26
@ElijahHamilton I made fixed version that works on my environment. Please let me know if it also works on yours.

[LatticeReverb_20230127.zip](https://github.com/ryukau/VSTPlugins/files/10518769/LatticeReverb_20230127.zip)

**Comment by ElijahHamilton** [comment] 2023-01-27 14:49
@ryukau I have tested it, and can confirm it now works!

**Comment by ElijahHamilton** [comment] 2023-01-27 14:54
And now, the plugin works in mono mode too.

**Comment by ryukau** [comment] 2023-01-28 02:53
@ElijahHamilton Thank you for reporting and testing! The fix is now released as 0.52.0.

If something is still now working correctly, feel free to add comment, or open another issue.

**Closed by ryukau** 2023-01-28 02:53 UTC
