### ISSUE TITLE
Some bugs new plugs

### ISSUE THREAD

**Issue by KlashKontakt** [ryukau/VSTPlugins#32] opened 2023-03-19 06:21 UTC
Arigato Takamitsu!

<img width="707" alt="Снимок экрана 2023-03-19 в 09 13 16" src="https://user-images.githubusercontent.com/87890552/226157201-1530114a-f954-4db7-9337-e1ac94bc079b.png">

ringmodspacer not visible after scan

Feedbackphaser 
<img width="764" alt="Снимок экрана 2023-03-19 в 09 18 44" src="https://user-images.githubusercontent.com/87890552/226157336-f17ea9ed-fe94-45ca-9b53-c62ab213eae8.png">
after add plugin in mixer

osx 13.2.1
Renoise 3.4.2
Thnx!

**Comment by ryukau** [comment] 2023-03-19 06:31
Just in case, have you deleted ComplexRotation and ImmediateSpacer from VST 3 directory? If they are present, there will be conflict of plugin GUID.

**Comment by ryukau** [comment] 2023-03-19 06:36
I confirmed the crash of FeedbackPhaser on Renoise. I'll work on it.

**Comment by KlashKontakt** [comment] 2023-03-19 06:59
https://youtu.be/ph2HCBUVWAQ

I conducted a test on instruments similar in spectral composition and unfortunately, when using the plugin, such a crack appeared

<img width="633" alt="Снимок экрана 2023-03-19 в 09 59 26" src="https://user-images.githubusercontent.com/87890552/226159421-fc2f4ec8-30ff-4ebe-9d8c-b62846378359.png">

**Comment by KlashKontakt** [comment] 2023-03-19 07:03
https://github.com/ryukau/VSTPlugins/issues/32#issuecomment-1475123473

Yes! yes i deleted everything and did a new plugin scan

**Comment by KlashKontakt** [comment] 2023-03-19 07:06
FeedbackPhaser very strange behavior of the plugin when connecting a chain. some kind of impact is present but it is not at all clear how to regulate it and what it does?

**Comment by ryukau** [comment] 2023-03-19 07:26
Okay, there seems to be 3 topics here.

1. RindModSpacer doesn't recognized by Renoise.
2. FeedbackPhaser crash.
3. How to use FeedbackPhaser.

I'll address one at a time to avoid confusion.

I'll start from 2. I found possible cause of FeedbackPhaser crash, and fixed it on de9ae8d. Could you try the one linked below? Please let me know if it still crashes or not.

[vst_macOS.zip](https://github.com/ryukau/VSTPlugins/files/11010439/vst_macOS.zip)

**Comment by ryukau** [comment] 2023-03-19 07:51
Just in case, steps to reproduce the crash on FeedbackPhaser v0.1.0 is following.

1. Load FeedbackPhaser in a mixer channel.
2. Input signal with 0 dB or louder amplitude, before opening plugin GUI.

When plugin GUI was opened before inputting signal, FeedbackPhaser didn't crash on my environment.

**Comment by KlashKontakt** [comment] 2023-03-19 08:28
FeedbackPhaser worked

**Comment by ryukau** [comment] 2023-03-19 08:53
Thanks for testing! So topic 2 is now finished.

I'll move to topic 1, which is about RindModSpacer. I suspect a bit of miscommunication was there, because of the language barrier.

Try removing ImmediateSpacer from your VST 3 folder, and see if RingModSpacer appears. In other words, do not install ImmediateSpacer and RingModSpacer at the same time.

I might be still misunderstanding the situation. Let me know if that's the case.

**Comment by ryukau** [comment] 2023-03-19 09:05
Also, the crack you observed in the video is the feature of RindModSpacer (or formerly ImmediateSpacer). This is a limitation of the method. For smoother sound, I'd recommend to use some side chain limiter.

**Comment by KlashKontakt** [comment] 2023-03-19 09:35
<img width="710" alt="Снимок экрана 2023-03-19 в 12 34 35" src="https://user-images.githubusercontent.com/87890552/226166232-c27997aa-5098-4fc5-b8d4-66d1e66d1299.png">

works but names

**Comment by ryukau** [comment] 2023-03-19 09:58
Probably some cache is remained in Renoise. Try following steps.

1. Temporary uninstall RindModSpacer.
2. Scan plugins on Renoise.
3. Install RindModSpacer again.
4. Scan plugins on Renoise.

If above steps doesn't solve the name issue, then it's probably better to ask a solution to Renoise support with link to this comment.

- 2 plugins with same GUID, but different name is installed.
- 1 of the plugin is uninstalled.
- After that, the window title of remaining plugin shows the removed plugin name.

**Comment by ryukau** [comment] 2023-03-19 10:23
I opened a discussion on topic 3, which is about how to use FeedbackPhaser. See following link.

- [How to Use FeedbackPhaser · ryukau/VSTPlugins · Discussion #33](https://github.com/ryukau/VSTPlugins/discussions/33)

**Comment by KlashKontakt** [comment] 2023-03-19 15:41
> Also, the crack you observed in the video is the feature of RindModSpacer (or formerly ImmediateSpacer). This is a limitation of the method. For smoother sound, I'd recommend to use some side chain limiter.

I was thinking about the crack that is formed in the lower part of the spectrum when mixing a sound similar in composition to the spectrum. maybe try adding some dithering to it? For some reason, it seems to me that this technology can help in terms of masking artifacts.

**Comment by KlashKontakt** [comment] 2023-03-19 15:43
> Probably some cache is remained in Renoise. Try following steps.
> 
> 1. Temporary uninstall RindModSpacer.
> 2. Scan plugins on Renoise.
> 3. Install RindModSpacer again.
> 4. Scan plugins on Renoise.
> 
> If above steps doesn't solve the name issue, then it's probably better to ask a solution to Renoise support with link to this comment.
> 
> * 2 plugins with same GUID, but different name is installed.
> * 1 of the plugin is uninstalled.
> * After that, the window title of remaining plugin shows the removed plugin name.

it worked. but here I found the errors of the renoise itself. they already had a similar problem. a little later I will write a bug report

**Comment by ryukau** [comment] 2023-03-19 18:29
It seems like the most of the issue is solved here. Last issue is the cracking or RindModSpacer. However, I honestly have no idea what you are talking about.

Dithering doesn't suppress nor eliminate low frequency components. It just adds subtle static noise to mask other kind of noise.

Ring modulation (or amplitude modulation) produces low frequency components as a sideband. Below is a equation of frequency components, where carrier and modulator are both sine wave. I got this equation from wikipedia ([link](https://en.wikipedia.org/wiki/Amplitude_modulation#Analysis)).

$$
y(t) = A \sin(2\pi f_c t) + \frac{1}{2}Am\left[\sin\left(2\pi \left[f_c + f_m\right] t + \phi\right) +  \sin\left(2\pi \left[f_c - f_m\right] t - \phi\right)\right].
$$

Notice the term:

$$
\sin\left(2\pi \left[f_c - f_m\right] t - \phi\right),
$$

where $f_c$ is carrier frequency and $f_m$ is modulator frequency.

For example, if $f_c = 1000$ Hz and $f_m = 1001$ Hz, then $f_c - f_m = 1$ Hz. This is the reason why ring modulation adds low frequency components.

**Comment by ryukau** [comment] 2023-03-20 20:46
Thanks for clarification. Now I get that it's about the distortion (or crackle).

The cause of crackle is the algorithm itself. Sidechain signal is full-wave rectified, then multiplies to input signal. This will surely cause harsh artifact.

Smoothing out the crackle is possible.

- Connect rectified sidechain signal into peak hold.
- Connect Peak hold output into a filter that doesn't overshoot.
- Convert filter output to gain reduction.
- Multiply the gain reduction to delayed input signal.

Delaying input signal is necessary to match the peak of input and filtered peak hold.

The algorithm above is called sidechain limiter with threshold set to $-\infty$ dB. In other words, smoothing out the crackle defeats the originality of the algorithm used in RindModSpacer. This is the reason I was saying to use sidechain limiter instead.

The above "smoothed" algorithm is already implemented as BasicLimiter/BasicLimiterAutoMake in this repository. I also believe that the algorithm is generic that any digital limiter use quite similar method.

More technical details are available in the links below. They are written in Japanese, so I'd recommend to use machine translation, if you are interested in.

- [リミッタの実装 (Limiter Implementation)](https://ryukau.github.io/filter_notes/limiter/limiter.html)
- [ピークホールドによるエンベロープ (Peak Hold Envelope)](https://ryukau.github.io/filter_notes/peak_hold_envelope/peak_hold_envelope.html)

---

It seems that the current topic is not a bug, but a character of the algorithm used. So I close this issue as completed.

@KlashKontakt Thanks for reporting. If you'd like to continue, feel free to open a discussion. I can answer some technical things.

**Closed by ryukau** 2023-03-20 20:46 UTC
